export type LayoutFamily = "cabinet" | "editorial" | "wizard" | "table" | "cards" | "research";
export type Density = "compact" | "regular" | "airy";
export type RadiusToken = "none" | "sm" | "md" | "lg" | "xl";
export type NavStyle = "sidebar" | "top" | "bottom" | "toc" | "steps" | "split" | "none";
export type FontPair = "serif-plex" | "literata" | "plex" | "newsreader" | "plex-mono" | "fraunces";

export interface ThemePassport {
  id: string;
  name: string;
  nameRu: string;
  family: LayoutFamily;
  nav: NavStyle;
  density: Density;
  radius: RadiusToken;
  shadow: "none" | "sm" | "md" | "lg";
  mode: "light" | "dark";
  fonts: FontPair;
  basedOn: "S" | "B";
  sourceRepo: "shadcn-ui/ui" | "twbs/bootstrap";
  sourceRef: string;
  tokens: Record<string, string>;
  notes: string;
}

const S = "shadcn-ui/ui" as const;
const B = "twbs/bootstrap" as const;

function t(
  partial: Omit<ThemePassport, "sourceRepo"> & { basedOn: "S" | "B" },
): ThemePassport {
  return {
    ...partial,
    sourceRepo: partial.basedOn === "S" ? S : B,
  };
}

export const THEMES: ThemePassport[] = [
  t({
    id: "mizan-emerald",
    name: "Mizan Emerald",
    nameRu: "Изумруд и золото",
    family: "cabinet",
    nav: "bottom",
    density: "regular",
    radius: "xl",
    shadow: "lg",
    mode: "dark",
    fonts: "fraunces",
    basedOn: "S",
    sourceRef: "sidebar-07 / blocks",
    tokens: {
      "--bg": "#04100c",
      "--bg-elev": "#071813",
      "--surface": "#0b2e23",
      "--fg": "#f8f4e9",
      "--muted": "#a8b6ae",
      "--accent": "#f0cf7a",
      "--accent-fg": "#04100c",
      "--line": "rgba(240,207,122,0.16)",
      "--ok": "#6ee1ae",
      "--danger": "#ff8b82",
    },
    notes: "Исходный бренд Мизан: изумруд, золото, весы. Нижняя навигация.",
  }),
  t({
    id: "ivory-ledger",
    name: "Ivory Ledger",
    nameRu: "Слоновая ведомость",
    family: "editorial",
    nav: "toc",
    density: "airy",
    radius: "sm",
    shadow: "none",
    mode: "light",
    fonts: "newsreader",
    basedOn: "B",
    sourceRef: "examples/cheatsheet",
    tokens: {
      "--bg": "#f6f1e6",
      "--bg-elev": "#fffaf1",
      "--surface": "#fffdf8",
      "--fg": "#2a2418",
      "--muted": "#6e6658",
      "--accent": "#5b4a32",
      "--accent-fg": "#f6f1e6",
      "--line": "rgba(42,36,24,0.12)",
      "--ok": "#3f6b4a",
      "--danger": "#9b3d32",
    },
    notes: "Светлая редакционная страница, антиква, тонкие разделители.",
  }),
  t({
    id: "graphite-desk",
    name: "Graphite Desk",
    nameRu: "Графитовый стол",
    family: "table",
    nav: "top",
    density: "compact",
    radius: "sm",
    shadow: "sm",
    mode: "dark",
    fonts: "plex-mono",
    basedOn: "S",
    sourceRef: "dashboard-01",
    tokens: {
      "--bg": "#121417",
      "--bg-elev": "#1a1d22",
      "--surface": "#22262c",
      "--fg": "#e8eaed",
      "--muted": "#9aa3ad",
      "--accent": "#b7c4d6",
      "--accent-fg": "#121417",
      "--line": "rgba(232,234,237,0.12)",
      "--ok": "#8fbf9a",
      "--danger": "#d98989",
    },
    notes: "Плотная таблица, моноширинные цифры.",
  }),
  t({
    id: "pearl-focus",
    name: "Pearl Focus",
    nameRu: "Жемчужный мастер",
    family: "wizard",
    nav: "steps",
    density: "airy",
    radius: "xl",
    shadow: "md",
    mode: "light",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "form-wizard pattern",
    tokens: {
      "--bg": "#f4f1ec",
      "--bg-elev": "#fffcf8",
      "--surface": "#ffffff",
      "--fg": "#1f2430",
      "--muted": "#6b7380",
      "--accent": "#3d5a73",
      "--accent-fg": "#f4f1ec",
      "--line": "rgba(31,36,48,0.1)",
      "--ok": "#3e7a5b",
      "--danger": "#b05454",
    },
    notes: "Один этап на экране, мягкая глубина.",
  }),
  t({
    id: "obsidian-command",
    name: "Obsidian Command",
    nameRu: "Обсидиановая команда",
    family: "cabinet",
    nav: "sidebar",
    density: "compact",
    radius: "none",
    shadow: "none",
    mode: "dark",
    fonts: "plex",
    basedOn: "S",
    sourceRef: "sidebar-05",
    tokens: {
      "--bg": "#070708",
      "--bg-elev": "#101113",
      "--surface": "#17181c",
      "--fg": "#f2f2f0",
      "--muted": "#8b8d93",
      "--accent": "#d2d2cc",
      "--accent-fg": "#070708",
      "--line": "rgba(242,242,240,0.12)",
      "--ok": "#8cba9a",
      "--danger": "#d27c76",
    },
    notes: "Почти чёрный фон, прямые карточки.",
  }),
  t({
    id: "sand-notebook",
    name: "Sand Notebook",
    nameRu: "Песочная тетрадь",
    family: "editorial",
    nav: "toc",
    density: "airy",
    radius: "md",
    shadow: "sm",
    mode: "light",
    fonts: "literata",
    basedOn: "B",
    sourceRef: "docs/examples/blog",
    tokens: {
      "--bg": "#efe4d0",
      "--bg-elev": "#f7edd9",
      "--surface": "#fbf4e6",
      "--fg": "#3b2e1d",
      "--muted": "#7a6a52",
      "--accent": "#8a5a32",
      "--accent-fg": "#fbf4e6",
      "--line": "rgba(59,46,29,0.12)",
      "--ok": "#4d6b3d",
      "--danger": "#a24a3a",
    },
    notes: "Тёплый бумажный фон, пометки источников.",
  }),
  t({
    id: "sapphire-grid",
    name: "Sapphire Grid",
    nameRu: "Сапфировая сетка",
    family: "cards",
    nav: "none",
    density: "regular",
    radius: "md",
    shadow: "md",
    mode: "dark",
    fonts: "plex",
    basedOn: "S",
    sourceRef: "card grid blocks",
    tokens: {
      "--bg": "#0b1220",
      "--bg-elev": "#121c30",
      "--surface": "#18243c",
      "--fg": "#e7eef8",
      "--muted": "#93a4bf",
      "--accent": "#7ea2d6",
      "--accent-fg": "#0b1220",
      "--line": "rgba(126,162,214,0.22)",
      "--ok": "#7dcea6",
      "--danger": "#e09090",
    },
    notes: "Карточный обзор с переходом в редактор.",
  }),
  t({
    id: "mint-journey",
    name: "Mint Journey",
    nameRu: "Мятный путь",
    family: "wizard",
    nav: "steps",
    density: "airy",
    radius: "xl",
    shadow: "sm",
    mode: "light",
    fonts: "plex",
    basedOn: "B",
    sourceRef: "examples/checkout",
    tokens: {
      "--bg": "#eef7f3",
      "--bg-elev": "#f7fcfa",
      "--surface": "#ffffff",
      "--fg": "#173028",
      "--muted": "#5d736b",
      "--accent": "#2f6f5e",
      "--accent-fg": "#f7fcfa",
      "--line": "rgba(23,48,40,0.1)",
      "--ok": "#2f6f5e",
      "--danger": "#b15b55",
    },
    notes: "Воздушный мастер, короткие подсказки.",
  }),
  t({
    id: "bronze-ledger",
    name: "Bronze Ledger",
    nameRu: "Бронзовая книга",
    family: "table",
    nav: "none",
    density: "compact",
    radius: "sm",
    shadow: "sm",
    mode: "dark",
    fonts: "plex-mono",
    basedOn: "S",
    sourceRef: "table dense",
    tokens: {
      "--bg": "#1a140f",
      "--bg-elev": "#241c16",
      "--surface": "#2c231b",
      "--fg": "#f0e6d8",
      "--muted": "#b3a394",
      "--accent": "#c08a54",
      "--accent-fg": "#1a140f",
      "--line": "rgba(192,138,84,0.22)",
      "--ok": "#8fbf8a",
      "--danger": "#d98980",
    },
    notes: "Бухгалтерская иерархия, тёплый металл.",
  }),
  t({
    id: "midnight-research",
    name: "Midnight Research",
    nameRu: "Полночное исследование",
    family: "research",
    nav: "split",
    density: "regular",
    radius: "md",
    shadow: "lg",
    mode: "dark",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "resizable two-pane",
    tokens: {
      "--bg": "#0c1018",
      "--bg-elev": "#141a24",
      "--surface": "#1b2230",
      "--fg": "#e9eef6",
      "--muted": "#9aa7bb",
      "--accent": "#9bb4d9",
      "--accent-fg": "#0c1018",
      "--line": "rgba(155,180,217,0.18)",
      "--ok": "#86c5a4",
      "--danger": "#d99292",
    },
    notes: "Расчёт слева, библиотека доводов справа.",
  }),
  t({
    id: "white-atlas",
    name: "White Atlas",
    nameRu: "Белый атлас",
    family: "cards",
    nav: "none",
    density: "airy",
    radius: "lg",
    shadow: "none",
    mode: "light",
    fonts: "plex",
    basedOn: "B",
    sourceRef: "examples/album",
    tokens: {
      "--bg": "#f7f7f5",
      "--bg-elev": "#ffffff",
      "--surface": "#ffffff",
      "--fg": "#1c1c1a",
      "--muted": "#6f6f6a",
      "--accent": "#2c2c2a",
      "--accent-fg": "#f7f7f5",
      "--line": "rgba(28,28,26,0.1)",
      "--ok": "#3d6b4f",
      "--danger": "#a33d3d",
    },
    notes: "Минимум рамок, модульная сетка.",
  }),
  t({
    id: "cedar-columns",
    name: "Cedar Columns",
    nameRu: "Кедровые колонны",
    family: "cabinet",
    nav: "sidebar",
    density: "regular",
    radius: "xl",
    shadow: "md",
    mode: "light",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "sidebar-03",
    tokens: {
      "--bg": "#f3eee6",
      "--bg-elev": "#faf6f0",
      "--surface": "#fffdf9",
      "--fg": "#2c3a30",
      "--muted": "#6b7a70",
      "--accent": "#3f6b52",
      "--accent-fg": "#faf6f0",
      "--line": "rgba(44,58,48,0.12)",
      "--ok": "#3f6b52",
      "--danger": "#a4544a",
    },
    notes: "Три области: навигация, расчёт, источники.",
  }),
  t({
    id: "silver-lines",
    name: "Silver Lines",
    nameRu: "Серебряные линии",
    family: "table",
    nav: "top",
    density: "compact",
    radius: "none",
    shadow: "none",
    mode: "light",
    fonts: "plex",
    basedOn: "B",
    sourceRef: "examples/dashboard",
    tokens: {
      "--bg": "#eef0f2",
      "--bg-elev": "#f7f8f9",
      "--surface": "#ffffff",
      "--fg": "#1b1f24",
      "--muted": "#66707a",
      "--accent": "#4a5560",
      "--accent-fg": "#ffffff",
      "--line": "rgba(27,31,36,0.14)",
      "--ok": "#3d6e55",
      "--danger": "#a14040",
    },
    notes: "Монохром, линейные таблицы, без теней.",
  }),
  t({
    id: "ink-reader",
    name: "Ink Reader",
    nameRu: "Чернильный читатель",
    family: "editorial",
    nav: "toc",
    density: "airy",
    radius: "sm",
    shadow: "none",
    mode: "light",
    fonts: "literata",
    basedOn: "S",
    sourceRef: "typography block",
    tokens: {
      "--bg": "#fbfaf6",
      "--bg-elev": "#ffffff",
      "--surface": "#ffffff",
      "--fg": "#161616",
      "--muted": "#5c5c5c",
      "--accent": "#1a1a1a",
      "--accent-fg": "#fbfaf6",
      "--line": "rgba(22,22,22,0.12)",
      "--ok": "#2f5d3a",
      "--danger": "#8f2f2f",
    },
    notes: "Документ со сносками, контраст заголовков.",
  }),
  t({
    id: "dawn-ribbon",
    name: "Dawn Ribbon",
    nameRu: "Лента рассвета",
    family: "editorial",
    nav: "top",
    density: "regular",
    radius: "none",
    shadow: "sm",
    mode: "light",
    fonts: "plex",
    basedOn: "B",
    sourceRef: "examples/navbars",
    tokens: {
      "--bg": "#f6f3ee",
      "--bg-elev": "#fff8ef",
      "--surface": "#ffffff",
      "--fg": "#2b2420",
      "--muted": "#74685e",
      "--accent": "#c46b3a",
      "--accent-fg": "#fff8ef",
      "--line": "rgba(43,36,32,0.1)",
      "--ok": "#4a6d45",
      "--danger": "#b04a40",
    },
    notes: "Верхняя лента, широкая одноколоночная форма.",
  }),
  t({
    id: "teal-workspace",
    name: "Teal Workspace",
    nameRu: "Бирюзовое пространство",
    family: "cabinet",
    nav: "sidebar",
    density: "regular",
    radius: "lg",
    shadow: "sm",
    mode: "dark",
    fonts: "plex",
    basedOn: "S",
    sourceRef: "sidebar-08",
    tokens: {
      "--bg": "#0b1c1c",
      "--bg-elev": "#122626",
      "--surface": "#173131",
      "--fg": "#e7f2f1",
      "--muted": "#90b0ad",
      "--accent": "#5fa8a0",
      "--accent-fg": "#0b1c1c",
      "--line": "rgba(95,168,160,0.22)",
      "--ok": "#5fa8a0",
      "--danger": "#d98b86",
    },
    notes: "Сворачиваемое меню, вкладки расчётов.",
  }),
  t({
    id: "velvet-cards",
    name: "Velvet Cards",
    nameRu: "Бархатные карты",
    family: "cards",
    nav: "none",
    density: "airy",
    radius: "xl",
    shadow: "lg",
    mode: "dark",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "card + dialog",
    tokens: {
      "--bg": "#140f16",
      "--bg-elev": "#1d1722",
      "--surface": "#261f2c",
      "--fg": "#f3ecf6",
      "--muted": "#b3a3bb",
      "--accent": "#d4c4a8",
      "--accent-fg": "#140f16",
      "--line": "rgba(212,196,168,0.18)",
      "--ok": "#8fbf9e",
      "--danger": "#d9899a",
    },
    notes: "Одна активная категория, крупные радиусы.",
  }),
  t({
    id: "slate-audit",
    name: "Slate Audit",
    nameRu: "Сланцевый аудит",
    family: "table",
    nav: "split",
    density: "compact",
    radius: "none",
    shadow: "none",
    mode: "dark",
    fonts: "plex-mono",
    basedOn: "S",
    sourceRef: "table + inspector",
    tokens: {
      "--bg": "#15171a",
      "--bg-elev": "#1c1f24",
      "--surface": "#23262c",
      "--fg": "#dfe3ea",
      "--muted": "#8b929c",
      "--accent": "#9aa7b8",
      "--accent-fg": "#15171a",
      "--line": "rgba(223,227,234,0.12)",
      "--ok": "#87b598",
      "--danger": "#c97c7c",
    },
    notes: "Формулы в инспекторе, минимум декора.",
  }),
  t({
    id: "alabaster-gallery",
    name: "Alabaster Gallery",
    nameRu: "Алебастровая галерея",
    family: "cards",
    nav: "none",
    density: "airy",
    radius: "xl",
    shadow: "sm",
    mode: "light",
    fonts: "serif-plex",
    basedOn: "B",
    sourceRef: "examples/album masonry",
    tokens: {
      "--bg": "#f4f0ea",
      "--bg-elev": "#fbf8f3",
      "--surface": "#ffffff",
      "--fg": "#2a2622",
      "--muted": "#726a62",
      "--accent": "#5a5148",
      "--accent-fg": "#fbf8f3",
      "--line": "rgba(42,38,34,0.1)",
      "--ok": "#456348",
      "--danger": "#a14b43",
    },
    notes: "Асимметрия, крупные заголовки.",
  }),
  t({
    id: "olive-journal",
    name: "Olive Journal",
    nameRu: "Оливковый журнал",
    family: "editorial",
    nav: "toc",
    density: "regular",
    radius: "md",
    shadow: "sm",
    mode: "light",
    fonts: "literata",
    basedOn: "B",
    sourceRef: "examples/blog numbered",
    tokens: {
      "--bg": "#eef0e6",
      "--bg-elev": "#f6f7ef",
      "--surface": "#fcfdf7",
      "--fg": "#2a3324",
      "--muted": "#66705a",
      "--accent": "#5b6b3a",
      "--accent-fg": "#fcfdf7",
      "--line": "rgba(42,51,36,0.12)",
      "--ok": "#5b6b3a",
      "--danger": "#a05040",
    },
    notes: "Последовательные записи, квитанция в конце.",
  }),
  t({
    id: "onyx-dock",
    name: "Onyx Dock",
    nameRu: "Ониксовый док",
    family: "cabinet",
    nav: "bottom",
    density: "compact",
    radius: "md",
    shadow: "lg",
    mode: "dark",
    fonts: "plex",
    basedOn: "S",
    sourceRef: "mobile dock pattern",
    tokens: {
      "--bg": "#0b0c0e",
      "--bg-elev": "#141518",
      "--surface": "#1c1d22",
      "--fg": "#f0f1f3",
      "--muted": "#8e929a",
      "--accent": "#cfd3da",
      "--accent-fg": "#0b0c0e",
      "--line": "rgba(207,211,218,0.16)",
      "--ok": "#86c49a",
      "--danger": "#d58a86",
    },
    notes: "Нижняя навигация, боковой лист редактора.",
  }),
  t({
    id: "sky-studio",
    name: "Sky Studio",
    nameRu: "Небесная студия",
    family: "research",
    nav: "top",
    density: "regular",
    radius: "md",
    shadow: "sm",
    mode: "light",
    fonts: "plex",
    basedOn: "S",
    sourceRef: "tabs + split",
    tokens: {
      "--bg": "#eef4f8",
      "--bg-elev": "#f7fbfe",
      "--surface": "#ffffff",
      "--fg": "#1c2a36",
      "--muted": "#5d7386",
      "--accent": "#3c7ca8",
      "--accent-fg": "#f7fbfe",
      "--line": "rgba(28,42,54,0.1)",
      "--ok": "#3c7a5c",
      "--danger": "#b05454",
    },
    notes: "Светло-голубой акцент, открытые поверхности.",
  }),
  t({
    id: "taupe-summary",
    name: "Taupe Summary",
    nameRu: "Тауповый итог",
    family: "research",
    nav: "none",
    density: "regular",
    radius: "sm",
    shadow: "sm",
    mode: "light",
    fonts: "newsreader",
    basedOn: "B",
    sourceRef: "examples/pricing two-col",
    tokens: {
      "--bg": "#ebe6df",
      "--bg-elev": "#f4f0ea",
      "--surface": "#fbf8f4",
      "--fg": "#2e2a26",
      "--muted": "#6f6860",
      "--accent": "#6a5e52",
      "--accent-fg": "#fbf8f4",
      "--line": "rgba(46,42,38,0.12)",
      "--ok": "#4d6750",
      "--danger": "#9c4d45",
    },
    notes: "Форма слева, высокий чек справа.",
  }),
  t({
    id: "cobalt-matrix",
    name: "Cobalt Matrix",
    nameRu: "Кобальтовая матрица",
    family: "table",
    nav: "none",
    density: "compact",
    radius: "sm",
    shadow: "none",
    mode: "dark",
    fonts: "plex-mono",
    basedOn: "S",
    sourceRef: "data table inline edit",
    tokens: {
      "--bg": "#0b1630",
      "--bg-elev": "#122044",
      "--surface": "#182a54",
      "--fg": "#e4ecff",
      "--muted": "#9aacd4",
      "--accent": "#7ea2ff",
      "--accent-fg": "#0b1630",
      "--line": "rgba(126,162,255,0.22)",
      "--ok": "#7dcea6",
      "--danger": "#e090a0",
    },
    notes: "Плотная сетка, правки в строках.",
  }),
  t({
    id: "moon-dialogue",
    name: "Moon Dialogue",
    nameRu: "Лунный диалог",
    family: "research",
    nav: "split",
    density: "regular",
    radius: "xl",
    shadow: "md",
    mode: "dark",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "chat + cards",
    tokens: {
      "--bg": "#101218",
      "--bg-elev": "#181b24",
      "--surface": "#20242f",
      "--fg": "#eef0f5",
      "--muted": "#a3a9b8",
      "--accent": "#c9c3b0",
      "--accent-fg": "#101218",
      "--line": "rgba(201,195,176,0.16)",
      "--ok": "#8fbfa8",
      "--danger": "#d98989",
    },
    notes: "Помощник рядом с карточками, форма полностью доступна.",
  }),
  t({
    id: "linen-review",
    name: "Linen Review",
    nameRu: "Льняной обзор",
    family: "editorial",
    nav: "toc",
    density: "airy",
    radius: "md",
    shadow: "none",
    mode: "light",
    fonts: "literata",
    basedOn: "B",
    sourceRef: "docs typography",
    tokens: {
      "--bg": "#f3efe6",
      "--bg-elev": "#faf7f0",
      "--surface": "#fffcf6",
      "--fg": "#2c291f",
      "--muted": "#6e6a5c",
      "--accent": "#4d5340",
      "--accent-fg": "#fffcf6",
      "--line": "rgba(44,41,31,0.1)",
      "--ok": "#4d5340",
      "--danger": "#9a4a40",
    },
    notes: "CSS-текстура льна, широкие поля.",
  }),
  t({
    id: "forest-console",
    name: "Forest Console",
    nameRu: "Лесная консоль",
    family: "cabinet",
    nav: "sidebar",
    density: "compact",
    radius: "sm",
    shadow: "sm",
    mode: "dark",
    fonts: "plex-mono",
    basedOn: "S",
    sourceRef: "tree sidebar",
    tokens: {
      "--bg": "#0a1610",
      "--bg-elev": "#102017",
      "--surface": "#16281d",
      "--fg": "#e5f0e8",
      "--muted": "#8eaa96",
      "--accent": "#8fbf9a",
      "--accent-fg": "#0a1610",
      "--line": "rgba(143,191,154,0.2)",
      "--ok": "#8fbf9a",
      "--danger": "#d98980",
    },
    notes: "Дерево категорий, нижний журнал формул.",
  }),
  t({
    id: "quartz-balance",
    name: "Quartz Balance",
    nameRu: "Кварцевый баланс",
    family: "research",
    nav: "split",
    density: "regular",
    radius: "lg",
    shadow: "sm",
    mode: "light",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "two-pane",
    tokens: {
      "--bg": "#f2f1f4",
      "--bg-elev": "#faf9fb",
      "--surface": "#ffffff",
      "--fg": "#26222a",
      "--muted": "#6c6672",
      "--accent": "#5a4e63",
      "--accent-fg": "#faf9fb",
      "--line": "rgba(38,34,42,0.1)",
      "--ok": "#3f6b52",
      "--danger": "#a4545c",
    },
    notes: "Две равные области: активы и условия.",
  }),
  t({
    id: "copper-steps",
    name: "Copper Steps",
    nameRu: "Медные ступени",
    family: "wizard",
    nav: "steps",
    density: "regular",
    radius: "lg",
    shadow: "md",
    mode: "dark",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "stepper",
    tokens: {
      "--bg": "#1a120e",
      "--bg-elev": "#241811",
      "--surface": "#2d1f16",
      "--fg": "#f6eadf",
      "--muted": "#c0a794",
      "--accent": "#d08a55",
      "--accent-fg": "#1a120e",
      "--line": "rgba(208,138,85,0.24)",
      "--ok": "#8fbf8a",
      "--danger": "#e08b84",
    },
    notes: "Вертикальная шкала этапов, медный акцент.",
  }),
  t({
    id: "monochrome-essential",
    name: "Monochrome Essential",
    nameRu: "Монохромная основа",
    family: "editorial",
    nav: "top",
    density: "airy",
    radius: "none",
    shadow: "none",
    mode: "light",
    fonts: "plex",
    basedOn: "B",
    sourceRef: "examples/starter",
    tokens: {
      "--bg": "#ffffff",
      "--bg-elev": "#f4f4f4",
      "--surface": "#ffffff",
      "--fg": "#111111",
      "--muted": "#5a5a5a",
      "--accent": "#111111",
      "--accent-fg": "#ffffff",
      "--line": "rgba(17,17,17,0.16)",
      "--ok": "#1f6b3a",
      "--danger": "#9b1c1c",
    },
    notes: "Высокая читаемость, крупные цели касания, минимум движения.",
  }),
  t({
    id: "kufic-night",
    name: "Kufic Night",
    nameRu: "Куфи ночь",
    family: "cabinet",
    nav: "bottom",
    density: "regular",
    radius: "xl",
    shadow: "lg",
    mode: "dark",
    fonts: "fraunces",
    basedOn: "S",
    sourceRef: "sidebar-07",
    tokens: { "--bg": "#05080f", "--bg-elev": "#0a101c", "--surface": "#121a2c", "--fg": "#e8eef8", "--muted": "#8d9bb0", "--accent": "#c9a46a", "--accent-fg": "#05080f", "--line": "rgba(201,164,106,0.18)", "--ok": "#6ec8a8", "--danger": "#e09088" },
    notes: "Тёмный кабинет, куфическое золото.",
  }),
  t({
    id: "madinah-stone",
    name: "Madinah Stone",
    nameRu: "Камень Медины",
    family: "editorial",
    nav: "top",
    density: "airy",
    radius: "md",
    shadow: "sm",
    mode: "light",
    fonts: "newsreader",
    basedOn: "B",
    sourceRef: "blog",
    tokens: { "--bg": "#f4efe6", "--bg-elev": "#fffaf3", "--surface": "#ebe3d6", "--fg": "#2b241c", "--muted": "#6f6558", "--accent": "#7a4e32", "--accent-fg": "#fffaf3", "--line": "rgba(43,36,28,0.12)", "--ok": "#3d6b4f", "--danger": "#9b3b32" },
    notes: "Светлый камень, спокойная редакция.",
  }),
  t({
    id: "andalus-lime",
    name: "Andalus Lime",
    nameRu: "Андалусская известь",
    family: "cards",
    nav: "bottom",
    density: "regular",
    radius: "lg",
    shadow: "md",
    mode: "light",
    fonts: "literata",
    basedOn: "S",
    sourceRef: "cards",
    tokens: { "--bg": "#f7f4ea", "--bg-elev": "#fffcf4", "--surface": "#ece7d8", "--fg": "#1f2a22", "--muted": "#5d6a60", "--accent": "#2f6f57", "--accent-fg": "#f7f4ea", "--line": "rgba(47,111,87,0.16)", "--ok": "#2f6f57", "--danger": "#b4564a" },
    notes: "Известь и сад Андалусии.",
  }),
  t({
    id: "bukhara-silk",
    name: "Bukhara Silk",
    nameRu: "Бухарский шёлк",
    family: "cabinet",
    nav: "sidebar",
    density: "compact",
    radius: "md",
    shadow: "md",
    mode: "dark",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "dashboard-01",
    tokens: { "--bg": "#1a1016", "--bg-elev": "#24151e", "--surface": "#331f2b", "--fg": "#f6e8ef", "--muted": "#b798a6", "--accent": "#d4a0b4", "--accent-fg": "#1a1016", "--line": "rgba(212,160,180,0.18)", "--ok": "#8fbf9a", "--danger": "#e08b84" },
    notes: "Тёмная ткань, боковая колонка.",
  }),
  t({
    id: "cairo-ink",
    name: "Cairo Ink",
    nameRu: "Каирские чернила",
    family: "research",
    nav: "toc",
    density: "compact",
    radius: "sm",
    shadow: "none",
    mode: "dark",
    fonts: "plex-mono",
    basedOn: "B",
    sourceRef: "dashboard",
    tokens: { "--bg": "#0c0d10", "--bg-elev": "#14161c", "--surface": "#1c1f28", "--fg": "#e7eadf", "--muted": "#8b9084", "--accent": "#e2c36b", "--accent-fg": "#0c0d10", "--line": "rgba(226,195,107,0.16)", "--ok": "#7dba8c", "--danger": "#d97a72" },
    notes: "Чернила и бумага ночного кабинета.",
  }),
  t({
    id: "fez-terracotta",
    name: "Fez Terracotta",
    nameRu: "Терракота Феса",
    family: "wizard",
    nav: "steps",
    density: "regular",
    radius: "lg",
    shadow: "sm",
    mode: "light",
    fonts: "fraunces",
    basedOn: "B",
    sourceRef: "checkout",
    tokens: { "--bg": "#f6ebe3", "--bg-elev": "#fff6f0", "--surface": "#ead7cc", "--fg": "#3a241c", "--muted": "#7a5a4e", "--accent": "#c45c32", "--accent-fg": "#fff6f0", "--line": "rgba(196,92,50,0.18)", "--ok": "#4d7a4a", "--danger": "#b33a32" },
    notes: "Мастер по ступеням, глина Феса.",
  }),
  t({
    id: "samarkand-tile",
    name: "Samarkand Tile",
    nameRu: "Плитка Самарканда",
    family: "cards",
    nav: "bottom",
    density: "airy",
    radius: "xl",
    shadow: "lg",
    mode: "dark",
    fonts: "literata",
    basedOn: "S",
    sourceRef: "cards",
    tokens: { "--bg": "#07151c", "--bg-elev": "#0c1f29", "--surface": "#12303c", "--fg": "#e4f4f2", "--muted": "#8aaeab", "--accent": "#3ec7c2", "--accent-fg": "#07151c", "--line": "rgba(62,199,194,0.18)", "--ok": "#6ee1ae", "--danger": "#ff8b82" },
    notes: "Бирюзовая плитка, карточки.",
  }),
  t({
    id: "hijaz-sand",
    name: "Hijaz Sand",
    nameRu: "Песок Хиджаза",
    family: "editorial",
    nav: "top",
    density: "airy",
    radius: "sm",
    shadow: "none",
    mode: "light",
    fonts: "newsreader",
    basedOn: "B",
    sourceRef: "cheatsheet",
    tokens: { "--bg": "#f3ead6", "--bg-elev": "#fbf4e4", "--surface": "#e7d9bc", "--fg": "#3b2e1c", "--muted": "#7a6a4e", "--accent": "#9a6b2f", "--accent-fg": "#fbf4e4", "--line": "rgba(154,107,47,0.2)", "--ok": "#4f7344", "--danger": "#a33e32" },
    notes: "Песчаная редакция, широкие поля.",
  }),
  t({
    id: "yemen-qamari",
    name: "Yemen Qamari",
    nameRu: "Йеменский камари",
    family: "cabinet",
    nav: "bottom",
    density: "regular",
    radius: "md",
    shadow: "md",
    mode: "dark",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "sidebar-07",
    tokens: { "--bg": "#0e1114", "--bg-elev": "#171c22", "--surface": "#222a32", "--fg": "#e8eef2", "--muted": "#8a97a3", "--accent": "#d8dde3", "--accent-fg": "#0e1114", "--line": "rgba(216,221,227,0.14)", "--ok": "#7dba8c", "--danger": "#d97a72" },
    notes: "Белый камень на ночи.",
  }),
  t({
    id: "maghreb-blue",
    name: "Maghreb Blue",
    nameRu: "Синь Магриба",
    family: "table",
    nav: "sidebar",
    density: "compact",
    radius: "sm",
    shadow: "sm",
    mode: "dark",
    fonts: "plex",
    basedOn: "B",
    sourceRef: "dashboard",
    tokens: { "--bg": "#071018", "--bg-elev": "#0c1a26", "--surface": "#13283a", "--fg": "#e6f0f8", "--muted": "#7f99ad", "--accent": "#4ea3e0", "--accent-fg": "#071018", "--line": "rgba(78,163,224,0.2)", "--ok": "#5ec8a4", "--danger": "#e08b84" },
    notes: "Таблица на синем, боковое меню.",
  }),
  t({
    id: "ottoman-ivory",
    name: "Ottoman Ivory",
    nameRu: "Османская слоновая",
    family: "wizard",
    nav: "steps",
    density: "airy",
    radius: "xl",
    shadow: "md",
    mode: "light",
    fonts: "fraunces",
    basedOn: "S",
    sourceRef: "stepper",
    tokens: { "--bg": "#f8f1e3", "--bg-elev": "#fffaf0", "--surface": "#eee4d0", "--fg": "#2c2418", "--muted": "#726752", "--accent": "#8a1e2b", "--accent-fg": "#fffaf0", "--line": "rgba(138,30,43,0.16)", "--ok": "#3f6b45", "--danger": "#8a1e2b" },
    notes: "Слоновая кость и кармин.",
  }),
  t({
    id: "tatar-green",
    name: "Tatar Green",
    nameRu: "Татарский зелёный",
    family: "cards",
    nav: "bottom",
    density: "regular",
    radius: "lg",
    shadow: "md",
    mode: "dark",
    fonts: "plex",
    basedOn: "S",
    sourceRef: "cards",
    tokens: { "--bg": "#0a140f", "--bg-elev": "#102018", "--surface": "#183226", "--fg": "#e7f3ea", "--muted": "#8eaa96", "--accent": "#8fd19a", "--accent-fg": "#0a140f", "--line": "rgba(143,209,154,0.18)", "--ok": "#8fd19a", "--danger": "#e08b84" },
    notes: "Зелень и нижняя навигация.",
  }),
  t({
    id: "persian-nasta",
    name: "Persian Nasta",
    nameRu: "Персидский наста",
    family: "editorial",
    nav: "toc",
    density: "airy",
    radius: "md",
    shadow: "sm",
    mode: "light",
    fonts: "literata",
    basedOn: "B",
    sourceRef: "blog",
    tokens: { "--bg": "#f6efe8", "--bg-elev": "#fff9f4", "--surface": "#eadfd4", "--fg": "#2a1f28", "--muted": "#6e5d68", "--accent": "#6b2d5b", "--accent-fg": "#fff9f4", "--line": "rgba(107,45,91,0.16)", "--ok": "#3f6b45", "--danger": "#9b3b32" },
    notes: "Светлая редакция, чернила насты.",
  }),
  t({
    id: "malay-gold",
    name: "Malay Gold",
    nameRu: "Малайское золото",
    family: "cabinet",
    nav: "split",
    density: "regular",
    radius: "xl",
    shadow: "lg",
    mode: "dark",
    fonts: "fraunces",
    basedOn: "S",
    sourceRef: "resizable",
    tokens: { "--bg": "#120e08", "--bg-elev": "#1c160c", "--surface": "#2a2112", "--fg": "#f7eed8", "--muted": "#b3a27a", "--accent": "#e0b24a", "--accent-fg": "#120e08", "--line": "rgba(224,178,74,0.2)", "--ok": "#7dba8c", "--danger": "#d97a72" },
    notes: "Раздвоенная колонка, тёплое золото.",
  }),
  t({
    id: "sahel-dusk",
    name: "Sahel Dusk",
    nameRu: "Сумерки Сахеля",
    family: "research",
    nav: "none",
    density: "compact",
    radius: "none",
    shadow: "none",
    mode: "dark",
    fonts: "plex-mono",
    basedOn: "B",
    sourceRef: "starter",
    tokens: { "--bg": "#16110d", "--bg-elev": "#211a14", "--surface": "#2c241c", "--fg": "#f0e6d8", "--muted": "#a89884", "--accent": "#e07a3d", "--accent-fg": "#16110d", "--line": "rgba(224,122,61,0.2)", "--ok": "#8fbf8a", "--danger": "#e08b84" },
    notes: "Исследование без рамки, закат.",
  }),
  t({
    id: "bosnia-frost",
    name: "Bosnia Frost",
    nameRu: "Боснийский иней",
    family: "table",
    nav: "top",
    density: "compact",
    radius: "sm",
    shadow: "sm",
    mode: "light",
    fonts: "plex",
    basedOn: "B",
    sourceRef: "dashboard",
    tokens: { "--bg": "#eef2f4", "--bg-elev": "#ffffff", "--surface": "#e2e8ec", "--fg": "#1c2428", "--muted": "#5c6b72", "--accent": "#2b5f73", "--accent-fg": "#ffffff", "--line": "rgba(43,95,115,0.16)", "--ok": "#2f6b4a", "--danger": "#9b3b32" },
    notes: "Холодная таблица, верхнее меню.",
  }),
  t({
    id: "kashmir-saffron",
    name: "Kashmir Saffron",
    nameRu: "Кашмирский шафран",
    family: "cards",
    nav: "bottom",
    density: "airy",
    radius: "lg",
    shadow: "md",
    mode: "light",
    fonts: "newsreader",
    basedOn: "S",
    sourceRef: "cards",
    tokens: { "--bg": "#fbf3e4", "--bg-elev": "#fff9ee", "--surface": "#f0e2c8", "--fg": "#2e2416", "--muted": "#7a6848", "--accent": "#c47b12", "--accent-fg": "#fff9ee", "--line": "rgba(196,123,18,0.2)", "--ok": "#4d7a4a", "--danger": "#b33a32" },
    notes: "Шафран на бумаге, карточки.",
  }),
  t({
    id: "nile-papyrus",
    name: "Nile Papyrus",
    nameRu: "Нильский папирус",
    family: "editorial",
    nav: "toc",
    density: "airy",
    radius: "md",
    shadow: "none",
    mode: "light",
    fonts: "literata",
    basedOn: "B",
    sourceRef: "blog",
    tokens: { "--bg": "#efe6c9", "--bg-elev": "#f7f0d8", "--surface": "#e4d8b4", "--fg": "#2a2718", "--muted": "#6b6548", "--accent": "#4a5c32", "--accent-fg": "#f7f0d8", "--line": "rgba(42,39,24,0.14)", "--ok": "#4a5c32", "--danger": "#9b3b32" },
    notes: "Папирус, оглавление слева.",
  }),
  t({
    id: "atlas-cedar",
    name: "Atlas Cedar",
    nameRu: "Кедр Атласа",
    family: "wizard",
    nav: "steps",
    density: "regular",
    radius: "lg",
    shadow: "md",
    mode: "dark",
    fonts: "serif-plex",
    basedOn: "S",
    sourceRef: "stepper",
    tokens: { "--bg": "#10160f", "--bg-elev": "#181f16", "--surface": "#243022", "--fg": "#e8f0e4", "--muted": "#93a48c", "--accent": "#c4b48a", "--accent-fg": "#10160f", "--line": "rgba(196,180,138,0.18)", "--ok": "#7dba8c", "--danger": "#d97a72" },
    notes: "Кедр и шаги мастера.",
  }),
  t({
    id: "haram-quiet",
    name: "Haram Quiet",
    nameRu: "Тишина харама",
    family: "cabinet",
    nav: "bottom",
    density: "regular",
    radius: "xl",
    shadow: "lg",
    mode: "dark",
    fonts: "fraunces",
    basedOn: "S",
    sourceRef: "sidebar-07",
    tokens: { "--bg": "#0b1210", "--bg-elev": "#121a18", "--surface": "#1b2924", "--fg": "#f2efe6", "--muted": "#9aa89f", "--accent": "#d7c49a", "--accent-fg": "#0b1210", "--line": "rgba(215,196,154,0.16)", "--ok": "#6ee1ae", "--danger": "#ff8b82" },
    notes: "Тихий изумруд, нижний док.",
  }),
];

export const DEFAULT_THEME_ID = "mizan-emerald";

export function getTheme(id: string): ThemePassport {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

export const LAYOUT_LABEL: Record<LayoutFamily, string> = {
  cabinet: "Кабинет",
  editorial: "Редакция",
  wizard: "Мастер",
  table: "Таблица",
  cards: "Карточки",
  research: "Исследование",
};
