import type { NisabMode, Profile, ProfileId } from "./types.ts";

export const PROFILES: Profile[] = [
  {
    id: "hanafi",
    name: "Ханафитский профиль",
    school: "hanafi",
    version: "2026.09.1",
    nisabGoldGrams: "87.48",
    nisabSilverGrams: "612.36",
    nisabMode: "silver",
    combineGoldSilverByValue: true,
    jewelryPersonalZakatable: true,
    livestockCashOk: true,
    cropCashOk: true,
    fitrCashOk: true,
    debtsDeductImmediate: true,
    tradeAtMarket: true,
    proxy25Allowed: false,
    notes:
      "Деньги и товары часто оценивают по серебряному нисабу. Украшения облагаются. Соединение золота и серебра по стоимости — позиция Абу Ханифы, не иджмаʿ. Массы 87,48/612,36 — метрология IR, не текст хадиса; 85/595 доступны в ZFA-профиле.",
    sourceIds: ["bukhari.1454", "ir.nisab.2026", "fiqh.jewelry.ikhtilaf", "fiqh.nisab.combine", "math.rate.1_40"],
    review: "translation_checked",
  },
  {
    id: "maliki",
    name: "Маликитский профиль",
    school: "maliki",
    version: "2026.09.1",
    nisabGoldGrams: "85",
    nisabSilverGrams: "595",
    nisabMode: "gold",
    combineGoldSilverByValue: false,
    jewelryPersonalZakatable: false,
    livestockCashOk: false,
    cropCashOk: false,
    fitrCashOk: false,
    debtsDeductImmediate: true,
    tradeAtMarket: true,
    proxy25Allowed: false,
    notes:
      "Личные носимые украшения, как правило, не облагаются. Нисаб денежных активов — золотой эквивалент (современная практика). Скот и урожай — в натуре, если не оговорено иное. Полные маликитские таблицы условий выпаса не исчерпаны.",
    sourceIds: ["bukhari.1454", "metrology.dinar.85", "fiqh.jewelry.ikhtilaf", "fiqh.nisab.combine"],
    review: "translation_checked",
  },
  {
    id: "shafii",
    name: "Шафиитский профиль",
    school: "shafii",
    version: "2026.09.1",
    nisabGoldGrams: "85",
    nisabSilverGrams: "595",
    nisabMode: "separate",
    combineGoldSilverByValue: false,
    jewelryPersonalZakatable: false,
    livestockCashOk: false,
    cropCashOk: false,
    fitrCashOk: false,
    debtsDeductImmediate: true,
    tradeAtMarket: true,
    proxy25Allowed: false,
    notes:
      "Ан-Навави: золото и серебро не дополняют нисаб друг друга. Украшения для ношения — обычно изъятие. Фитр — ṣāʿ продукта, не деньги (денежная замена не разрешена этим профилем).",
    sourceIds: ["bukhari.1454", "bukhari.1503", "fiqh.nisab.combine", "fiqh.jewelry.ikhtilaf", "metrology.dinar.85"],
    review: "translation_checked",
  },
  {
    id: "hanbali",
    name: "Ханбалитский профиль",
    school: "hanbali",
    version: "2026.09.1",
    nisabGoldGrams: "85",
    nisabSilverGrams: "595",
    nisabMode: "separate",
    combineGoldSilverByValue: false,
    jewelryPersonalZakatable: false,
    livestockCashOk: false,
    cropCashOk: false,
    fitrCashOk: false,
    debtsDeductImmediate: true,
    tradeAtMarket: true,
    proxy25Allowed: false,
    notes: "Близок к шафиитскому в вопросах соединения металлов и украшений. Денежная замена фитра и скота этим профилем не разрешается.",
    sourceIds: ["bukhari.1454", "fiqh.nisab.combine", "fiqh.jewelry.ikhtilaf", "metrology.dinar.85"],
    review: "translation_checked",
  },
  {
    id: "islamic-relief-silver",
    name: "Islamic Relief (серебряный нисаб)",
    school: "institutional",
    version: "2026.09.1-public-pages",
    nisabGoldGrams: "87.48",
    nisabSilverGrams: "612.36",
    nisabMode: "silver",
    combineGoldSilverByValue: true,
    jewelryPersonalZakatable: true,
    livestockCashOk: true,
    cropCashOk: true,
    fitrCashOk: true,
    debtsDeductImmediate: true,
    tradeAtMarket: true,
    proxy25Allowed: true,
    notes:
      "Публичные страницы IR 2026: 87,48 г / 612,36 г, рекомендация серебра. Полный внутренний manual не сверен. 25 % proxy доступен только как явная оценка, не как скрытое правило IR.",
    sourceIds: ["ir.nisab.2026", "ir.uk.calculator", "math.rate.1_40", "nzf.proxy25.unverified"],
    review: "institutional_page_checked",
  },
  {
    id: "zfa-gold-85",
    name: "Золотой нисаб 85 г (ZFA-стиль)",
    school: "institutional",
    version: "2026.09.1",
    nisabGoldGrams: "85",
    nisabSilverGrams: "595",
    nisabMode: "gold",
    combineGoldSilverByValue: false,
    jewelryPersonalZakatable: true,
    livestockCashOk: true,
    cropCashOk: true,
    fitrCashOk: true,
    debtsDeductImmediate: true,
    tradeAtMarket: true,
    proxy25Allowed: true,
    notes:
      "85 г золота — распространённый институциональный перевод 20 динаров. Ярлык «Zakat Foundation» исходного файла не заменяет отсутствующий первичный PDF; профиль назван по метрологии, не как сертификация ZFA.",
    sourceIds: ["metrology.dinar.85", "metrology.dirham.595", "math.rate.1_40"],
    review: "institutional_page_checked",
  },
  {
    id: "custom",
    name: "Пользовательский профиль",
    school: "custom",
    version: "2026.09.1",
    nisabGoldGrams: "85",
    nisabSilverGrams: "595",
    nisabMode: "gold",
    combineGoldSilverByValue: false,
    jewelryPersonalZakatable: true,
    livestockCashOk: true,
    cropCashOk: true,
    fitrCashOk: true,
    debtsDeductImmediate: true,
    tradeAtMarket: true,
    proxy25Allowed: true,
    notes: "Параметры нисаба и режим задаёт пользователь. Не является мазхабом. Все выбранные числа маркируются как ручной ввод.",
    sourceIds: ["metrology.dinar.85"],
    review: "unverified",
  },
];

export function getProfile(id: ProfileId): Profile {
  const p = PROFILES.find((x) => x.id === id);
  if (!p) throw new Error(`Unknown profile ${id}`);
  return p;
}

export function resolveNisabGrams(
  profile: Profile,
  override?: { goldGrams?: string; silverGrams?: string; mode?: NisabMode },
): { gold: string; silver: string; mode: NisabMode } {
  return {
    gold: override?.goldGrams || profile.nisabGoldGrams,
    silver: override?.silverGrams || profile.nisabSilverGrams,
    mode: override?.mode || profile.nisabMode,
  };
}
