import type { RuleRecord } from "./types.ts";

export const RULES: RuleRecord[] = [
  {
    ruleId: "rule.money.1_40",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "money,metals,trade,investments,crypto",
    conditions: "нисаб выбранного профиля; хауль подтверждён пользователем",
    exceptions: "хауль не подтверждён; нет курса; актив неликвидный",
    formula: "net * 1/40 после допустимых вычетов; не меньше 0",
    sourceIds: ["bukhari.1454", "math.rate.1_40"],
    tests: ["100000 → 2500", "два по 50000", "100 USD * 90"],
    review: "primary_text_checked",
  },
  {
    ruleId: "rule.nisab.profile",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "nisab",
    conditions: "есть цена металла в базовой валюте",
    exceptions: "режим separate не соединяет металлы (шафии/ханбали)",
    formula: "goldGrams*goldPrice | silverGrams*silverPrice | min/max по режиму",
    sourceIds: ["bukhari.1447", "bukhari.1454", "metrology.dinar.85", "ir.nisab.2026", "fiqh.nisab.combine"],
    tests: ["ниже / на пороге / выше"],
    review: "translation_checked",
  },
  {
    ruleId: "rule.metals.purity",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "metals",
    conditions: "масса и проба",
    exceptions: "украшения personal_wear в профилях без jewelryPersonalZakatable",
    formula: "grams * purity/1000 * pricePerGram",
    sourceIds: ["bukhari.1454", "fiqh.jewelry.ikhtilaf"],
    tests: ["100 г * 585 = 58.5 г"],
    review: "translation_checked",
  },
  {
    ruleId: "rule.jewelry.profile",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali"],
    domain: "metals.jewelry",
    conditions: "форма jewelry и use personal_wear",
    exceptions: "торговля и накопление облагаются во всех профилях",
    formula: "include iff profile.jewelryPersonalZakatable",
    sourceIds: ["fiqh.jewelry.ikhtilaf"],
    tests: ["hanafi include", "shafii exclude wear"],
    review: "translation_checked",
  },
  {
    ruleId: "rule.invest.modes",
    version: "1",
    profileIds: ["islamic-relief-silver", "zfa-gold-85", "custom", "hanafi", "maliki", "shafii", "hanbali"],
    domain: "investments",
    conditions: "явный режим",
    exceptions: "proxy_25 только если profile.proxy25Allowed; asset_fraction без доли = incomplete",
    formula: "100% | amount*fraction | amount*0.25 marked",
    sourceIds: ["nzf.proxy25.unverified", "ir.uk.calculator"],
    tests: ["100000 trade", "40%", "25% → 25000"],
    review: "unverified",
  },
  {
    ruleId: "rule.invest.proxy25",
    version: "1",
    profileIds: ["islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "investments.proxy",
    conditions: "пользователь явно выбрал proxy_25",
    exceptions: "не применяется молча",
    formula: "market * 1/4, пометить как оценку",
    sourceIds: ["nzf.proxy25.unverified"],
    tests: ["625 при 2.5% если нисаб выполнен"],
    review: "unverified",
  },
  {
    ruleId: "rule.sheep.bukhari1454",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "livestock.sheep",
    conditions: "саима, хауль, целые головы",
    exceptions: "кормовой скот",
    formula: "40-120:1; 121-200:2; 201-300:3; ≥301: floor(n/100)",
    sourceIds: ["bukhari.1454"],
    tests: ["39,40,120,121,200,201,300,301,399,400"],
    review: "primary_text_checked",
  },
  {
    ruleId: "rule.camel.bukhari1454",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "livestock.camel",
    conditions: "саима, хауль",
    exceptions: "n<5",
    formula: "таблица возрастов; >120 комбинации 40/50",
    sourceIds: ["bukhari.1454"],
    tests: ["4,5,24,25,35,36,120,121"],
    review: "primary_text_checked",
  },
  {
    ruleId: "rule.cattle.abudawud1576",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "livestock.cattle",
    conditions: "саима",
    exceptions: "не Бухари 1454",
    formula: "30 tabi, 40 musinna, далее 30/40",
    sourceIds: ["abudawud.1576"],
    tests: ["29,30,39,40,59,60"],
    review: "primary_text_checked",
  },
  {
    ruleId: "rule.crops.bukhari1483",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "crops",
    conditions: "масса в кг, тип полива",
    exceptions: "смешанный без доли; неизвестный полив",
    formula: "natural: mass/10 кг; costly: mass/20 кг",
    sourceIds: ["bukhari.1483", "bukhari.1447", "quran.6.141"],
    tests: ["1000 кг → 100 кг / 50 кг"],
    review: "primary_text_checked",
  },
  {
    ruleId: "rule.crops.mixed.user_share",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "crops.mixed",
    conditions: "доля естественного полива задана пользователем",
    exceptions: "не угадывать единую ставку",
    formula: "nat*1/10 + cost*1/20",
    sourceIds: ["bukhari.1483"],
    tests: [],
    review: "unverified",
  },
  {
    ruleId: "rule.rikaz.bukhari6912",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "rikaz",
    conditions: "classifiedAsRikaz === true",
    exceptions: "обычная находка",
    formula: "amount * 1/5",
    sourceIds: ["bukhari.6912"],
    tests: ["10000 → 2000"],
    review: "primary_text_checked",
  },
  {
    ruleId: "rule.fitr.bukhari1503",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "fitr.food",
    conditions: "целое число людей",
    exceptions: "дробные люди отклоняются",
    formula: "n * 1 ṣāʿ",
    sourceIds: ["bukhari.1503", "bukhari.1506"],
    tests: ["4 человека → 4 ṣāʿ"],
    review: "primary_text_checked",
  },
  {
    ruleId: "rule.fitr.cash.local",
    version: "1",
    profileIds: ["hanafi", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "fitr.cash",
    conditions: "profile.fitrCashOk и задан эквивалент",
    exceptions: "шафии/малики/ханбали — отказ",
    formula: "people * cashPerPerson",
    sourceIds: ["bukhari.1503"],
    tests: ["4*300=1200 тестовые"],
    review: "unverified",
  },
  {
    ruleId: "rule.trade.market",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "trade",
    conditions: "торговые остатки",
    exceptions: "доля собственника",
    formula: "(inventory+cash+receivables-payables)*share",
    sourceIds: ["ir.uk.calculator"],
    tests: [],
    review: "institutional_page_checked",
  },
  {
    ruleId: "rule.property.split",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "real_estate",
    conditions: "purpose",
    exceptions: "личное пользование",
    formula: "personal exclude; rental = income; trade = value",
    sourceIds: ["ir.uk.calculator"],
    tests: [],
    review: "unverified",
  },
  {
    ruleId: "rule.debts.split",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "debts",
    conditions: "immediate payable / collectible receivable",
    exceptions: "отрицательный закят запрещён",
    formula: "deduct immediate; add collectible",
    sourceIds: ["ir.uk.calculator"],
    tests: ["долги > активов → 0"],
    review: "institutional_page_checked",
  },
  {
    ruleId: "rule.crypto.ijtihad",
    version: "1",
    profileIds: ["hanafi", "maliki", "shafii", "hanbali", "islamic-relief-silver", "zfa-gold-85", "custom"],
    domain: "crypto",
    conditions: "availability=liquid и есть цена",
    exceptions: "staked/defi/locked incomplete",
    formula: "qty*price, затем в денежную базу",
    sourceIds: ["crypto.screening.opinions"],
    tests: [],
    review: "unverified",
  },
];
