import type { SourceRecord } from "./types.ts";

const RETRIEVED = "2026-09-09";

export const SOURCES: SourceRecord[] = [
  {
    sourceId: "quran.2.43",
    type: "quran",
    title: "Коран 2:43",
    author: "Откровение",
    url: "https://quran.com/2/43",
    locator: "сура 2 аль-Бакара, аят 43",
    language: "ar",
    translator: "Э. Кулиев (рус.); Saheeh International (en)",
    retrievedAt: RETRIEVED,
    terms: "текст Корана; перевод — мнение переводчика",
    review: "primary_text_checked",
    arabic: "وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ وَارْكَعُوا مَعَ الرَّاكِعِينَ",
    translationRu: "И совершайте намаз, выплачивайте закят и кланяйтесь вместе с кланяющимися.",
    translationEn: "And establish prayer and give zakah and bow with those who bow [in worship and obedience].",
    notes: "Общее предписание закята. Не задаёт ставки, нисаб, виды имущества и не говорит о криптоактивах.",
  },
  {
    sourceId: "quran.9.60",
    type: "quran",
    title: "Коран 9:60",
    author: "Откровение",
    url: "https://quran.com/9/60",
    locator: "сура 9 ат-Тауба, аят 60",
    language: "ar",
    translator: "Э. Кулиев; Saheeh International",
    retrievedAt: RETRIEVED,
    terms: "текст Корана",
    review: "primary_text_checked",
    arabic:
      "إِنَّمَا الصَّدَقَاتُ لِلْفُقَرَاءِ وَالْمَسَاكِينِ وَالْعَامِلِينَ عَلَيْهَا وَالْمُؤَلَّفَةِ قُلُوبُهُمْ وَفِي الرِّقَابِ وَالْغَارِمِينَ وَفِي سَبِيلِ اللَّهِ وَابْنِ السَّبِيلِ فَرِيضَةً مِنَ اللَّهِ وَاللَّهُ عَلِيمٌ حَكِيمٌ",
    translationRu:
      "Пожертвования предназначены для бедных, нищих, тех, кто занимается (сбором и раздачей) закята, тех, чьи сердца хотят привлечь к исламу, для выкупа рабов, для должников, для трат на пути Аллаха и для путников. Так предписано Аллахом. Аллах — Знающий, Мудрый.",
    notes: "Восемь категорий получателей. Калькулятор не переводит средства и не назначает получателя автоматически.",
  },
  {
    sourceId: "quran.9.103",
    type: "quran",
    title: "Коран 9:103",
    author: "Откровение",
    url: "https://quran.com/9/103",
    locator: "сура 9 ат-Тауба, аят 103",
    language: "ar",
    translator: "Э. Кулиев; Saheeh International",
    retrievedAt: RETRIEVED,
    terms: "текст Корана",
    review: "primary_text_checked",
    arabic: "خُذْ مِنْ أَمْوَالِهِمْ صَدَقَةً تُطَهِّرُهُمْ وَتُزَكِّيهِم بِهَا وَصَلِّ عَلَيْهِمْ إِنَّ صَلَاتَكَ سَكَنٌ لَّهُمْ وَاللَّهُ سَمِيعٌ عَلِيمٌ",
    translationRu: "Бери из их имущества милостыню, которой ты очистишь и возвысишь их…",
    notes: "Предписание брать садаку из имущества. Не фиксирует 2,5 % и не описывает современные инструменты.",
  },
  {
    sourceId: "quran.6.141",
    type: "quran",
    title: "Коран 6:141",
    author: "Откровение",
    url: "https://quran.com/6/141",
    locator: "сура 6 аль-Анʿам, аят 141",
    language: "ar",
    translator: "Э. Кулиев; Saheeh International",
    retrievedAt: RETRIEVED,
    terms: "текст Корана",
    review: "primary_text_checked",
    arabic: "وَآتُوا حَقَّهُ يَوْمَ حَصَادِهِ",
    translationRu: "…и отдавайте должное в день сбора урожая…",
    notes: "Указывает на выплату при сборе урожая (без хауля). Ставка 10/5 % берётся не из этого аята, а из хадиса.",
  },
  {
    sourceId: "bukhari.1454",
    type: "hadith",
    title: "Сахих аль-Бухари 1454",
    author: "аль-Бухари; передатчик Анас, письмо Абу Бакра",
    url: "https://sunnah.com/bukhari:1454",
    locator: "Kitāb al-Zakāt, Bāb zakāt al-ghanam; номер 1454 (нумерация sunnah.com)",
    language: "ar/en",
    translator: "Muhsin Khan (en, sunnah.com)",
    retrievedAt: RETRIEVED,
    edition: "Сахих; оценка сборника",
    terms: "текст хадиса; пояснения переводчика в скобках не являются арабским текстом",
    review: "primary_text_checked",
    arabic: undefined,
    translationEn:
      "Sheep: 40–120 → one sheep; 121–200 → two; 201–300 → three; over 300 → one sheep per extra hundred. Camels: detailed age brackets. Silver: one-fortieth; below 200 dirhams none.",
    notes:
      "Таблицы овец и верблюдов и ставка серебра 1/40 при 200 дирхемах. Золото, современные деньги, КРС и крипто в этом хадисе не описаны. На границе 120 овец — одна овца, не две и не floor(n/40).",
  },
  {
    sourceId: "bukhari.1447",
    type: "hadith",
    title: "Сахих аль-Бухари 1447",
    author: "аль-Бухари; Абу Саʿид аль-Худри",
    url: "https://sunnah.com/bukhari:1447",
    locator: "Kitāb al-Zakāt; 1447",
    language: "ar/en",
    translator: "Muhsin Khan — скобки переводчика не часть арабского текста",
    retrievedAt: RETRIEVED,
    edition: "Сахих",
    terms: "арабский текст хадиса vs. пояснения издания",
    review: "primary_text_checked",
    arabic:
      "لَيْسَ فِيمَا دُونَ خَمْسِ ذَوْدٍ صَدَقَةٌ مِنَ الإِبِلِ، وَلَيْسَ فِيمَا دُونَ خَمْسِ أَوَاقٍ صَدَقَةٌ، وَلَيْسَ فِيمَا دُونَ خَمْسَةِ أَوْسُقٍ صَدَقَةٌ",
    translationEn:
      "No zakat on less than five camels; no zakat on less than five awāq (silver); no zakat on less than five awsuq.",
    notes:
      "Арабский текст не называет 20 динаров. Упоминание золота в английском издании — пояснение переводчика, не хадис. 1 wasq = 60 ṣāʿ в комментарии издания; перевод ṣāʿ в килограммы зависит от вида продукции и не универсален.",
  },
  {
    sourceId: "bukhari.1483",
    type: "hadith",
    title: "Сахих аль-Бухари 1483",
    author: "аль-Бухари; Ибн Умар",
    url: "https://sunnah.com/bukhari:1483",
    locator: "Kitāb al-Zakāt; 1483",
    language: "ar/en",
    translator: "Muhsin Khan",
    retrievedAt: RETRIEVED,
    edition: "Сахих",
    terms: "текст хадиса",
    review: "primary_text_checked",
    arabic: "فِيمَا سَقَتِ السَّمَاءُ وَالْعُيُونُ أَوْ كَانَ عَثَرِيًّا الْعُشْرُ، وَمَا سُقِيَ بِالنَّضْحِ نِصْفُ الْعُشْرِ",
    translationEn:
      "On that which is watered by rain, springs or ʿatharī: one-tenth; on that which is watered by a well (naḍḥ): half of one-tenth.",
    translationRu: "С того, что полито дождём, родниками или самотёком — десятая часть; с того, что полито из колодца — половина десятины.",
    notes: "Ставки 10 % и 5 %. Порог 5 васков — из 1447, не из 1483. Смешанный полив этим хадисом не решён.",
  },
  {
    sourceId: "bukhari.1503",
    type: "hadith",
    title: "Сахих аль-Бухари 1503",
    author: "аль-Бухари; Ибн Умар",
    url: "https://sunnah.com/bukhari:1503",
    locator: "Kitāb al-Zakāt; 1503",
    language: "ar/en",
    translator: "Muhsin Khan — «1 ṣāʿ ≈ 3 кг» в скобках издания не является текстом хадиса",
    retrievedAt: RETRIEVED,
    edition: "Сахих",
    terms: "текст хадиса",
    review: "primary_text_checked",
    arabic:
      "فَرَضَ رَسُولُ اللَّهِ صلى الله عليه وسلم زَكَاةَ الْفِطْرِ صَاعًا مِنْ تَمْرٍ، أَوْ صَاعًا مِنْ شَعِيرٍ عَلَى الْعَبْدِ وَالْحُرِّ، وَالذَّكَرِ وَالأُنْثَى، وَالصَّغِيرِ وَالْكَبِيرِ مِنَ الْمُسْلِمِينَ، وَأَمَرَ بِهَا أَنْ تُؤَدَّى قَبْلَ خُرُوجِ النَّاسِ إِلَى الصَّلاَةِ",
    translationEn: "One ṣāʿ of dates or barley on every Muslim, before the ʿĪd prayer.",
    notes:
      "Норма — 1 ṣāʿ фиников или ячменя. Денежный эквивалент и перевод в кг — местная методика, не текст хадиса. Срок — до праздничной молитвы.",
  },
  {
    sourceId: "bukhari.1506",
    type: "hadith",
    title: "Сахих аль-Бухари 1506 / 1507",
    author: "аль-Бухари",
    url: "https://sunnah.com/bukhari:1506",
    locator: "Kitāb al-Zakāt; 1506–1507",
    language: "ar/en",
    retrievedAt: RETRIEVED,
    terms: "текст хадиса",
    review: "primary_text_checked",
    notes: "Дополнительные риваяты фитра. Используются вместе с 1503. Не фиксируют рублёвую сумму.",
  },
  {
    sourceId: "bukhari.6912",
    type: "hadith",
    title: "Сахих аль-Бухари 6912",
    author: "аль-Бухари; Абу Хурайра",
    url: "https://sunnah.com/bukhari:6912",
    locator: "Kitāb al-Diyāt; 6912",
    language: "ar/en",
    translator: "Muhsin Khan",
    retrievedAt: RETRIEVED,
    edition: "Сахих",
    terms: "текст хадиса",
    review: "primary_text_checked",
    arabic: "وَفِي الرِّكَازِ الْخُمُسُ",
    translationEn: "And in rikāz (buried treasure) there is one-fifth.",
    translationRu: "И в риказе — пятая часть.",
    notes:
      "Риказ — клад доисламского/скрытого сокровища в классическом смысле, не любая находка и не любая добыча. Ставка 1/5 применяется только при подтверждённой классификации.",
  },
  {
    sourceId: "abudawud.1576",
    type: "hadith",
    title: "Сунан Аби Дауд 1576 (ср. ат-Тирмизи 623)",
    author: "Абу Дауд; Муʿаз ибн Джабаль",
    url: "https://sunnah.com/abudawud:1576",
    locator: "Kitāb al-Zakāt, Bāb fī zakāt al-sāʾima; 1576",
    language: "ar/en",
    translator: "sunnah.com; оценка аль-Албани: сахих (для близкого 1578)",
    retrievedAt: RETRIEVED,
    edition: "Сунан Аби Дауд",
    terms: "КРС отсутствует в Бухари 1454",
    review: "primary_text_checked",
    translationEn: "For every 30 cattle a tabīʿ/tabīʿah (1 year); for every 40 a musinnah (2 years). Pasturing animals (sāʾima).",
    notes: "Таблица КРС. Условие выпаса (саима) и хауль исследуются в фикхе отдельно. Не floor(n/30) как универсальная формула для всех стад.",
  },
  {
    sourceId: "fiqh.jewelry.ikhtilaf",
    type: "fiqh",
    title: "Расхождение о женских украшениях",
    author: "четыре мазхаба (сводка)",
    url: "https://islamqa.info/en/answers/59864",
    locator: "ханафи: облагается; шафии/малики/ханбали: носимые украшения, как правило, не облагаются при условиях",
    language: "ru/en/ar",
    retrievedAt: RETRIEVED,
    terms: "не выдавать одно мнение за иджмаʿ",
    review: "translation_checked",
    notes: "Ханафиты облагают золото и серебро в любом виде. Другие школы освобождают личные украшения при отсутствии накопления/торговли. Профиль выбирает правило явно.",
  },
  {
    sourceId: "fiqh.nisab.combine",
    type: "fiqh",
    title: "Соединение золота и серебра для нисаба",
    author: "ан-Навави, аль-Маджмуʿ 5/504; исламQA 144734",
    url: "https://islamqa.info/en/answers/144734",
    locator: "большинство: не соединять; Абу Ханифа и ряд иракцев: соединять по стоимости",
    language: "en/ar",
    retrievedAt: RETRIEVED,
    terms: "ихтиляф",
    review: "translation_checked",
    notes: "Шафии/ханбали: золото и серебро не дополняют нисаб друг друга. Ханафи: соединение. Для современных денег — отдельная аналогия, не текст хадиса.",
  },
  {
    sourceId: "metrology.dinar.85",
    type: "metrology",
    title: "Современный перевод 20 динаров ≈ 85 г",
    author: "распространённая метрология (4,25 г × 20)",
    url: "https://islamicrelief.org.au/our-work/islamic-giving/zakat/zakat-on-gold/",
    locator: "не хадис; расчёт массы динара",
    language: "en",
    retrievedAt: RETRIEVED,
    terms: "метрология, не откровение",
    review: "institutional_page_checked",
    notes: "Хадис говорит о динарах/дирхемах. 85 г — современный перевод веса динара. Не единственный: 87,48 г использует другой вес.",
  },
  {
    sourceId: "metrology.dirham.595",
    type: "metrology",
    title: "Современный перевод 200 дирхемов ≈ 595 г",
    author: "распространённая метрология (≈2,975 г × 200)",
    url: "https://islamicrelief.org.au/our-work/islamic-giving/zakat/zakat-on-gold/",
    locator: "не хадис",
    language: "en",
    retrievedAt: RETRIEVED,
    terms: "метрология",
    review: "institutional_page_checked",
    notes: "200 дирхемов из Бухари 1454/1447. 595 г — один из современных переводов. 612,36 г — другой (Islamic Relief).",
  },
  {
    sourceId: "ir.nisab.2026",
    type: "institutional",
    title: "Islamic Relief: нисаб 87,48 г Au / 612,36 г Ag",
    author: "Islamic Relief Canada / UK (публичные страницы, 2026)",
    url: "https://www.islamicreliefcanada.org/our-work/zakat/nisab",
    locator: "страница Nisab; UK calculator 2026-09-09",
    language: "en",
    retrievedAt: RETRIEVED,
    edition: "публичная веб-страница, не полный внутренний manual",
    terms: "методика организации, не иджмаʿ",
    review: "institutional_page_checked",
    notes:
      "IR рекомендует серебряный нисаб (ханафитская практика, чтобы порог был ниже). Другие мазхабы — золотой. Полный внутренний документ IR 2026 в ходе этой работы не получен. Не заявляется как AAOIFI.",
  },
  {
    sourceId: "ir.uk.calculator",
    type: "institutional",
    title: "Islamic Relief UK Zakat calculator (описание шагов)",
    author: "Islamic Relief UK",
    url: "https://www.islamic-relief.org.uk/giving/islamic-giving/zakat/zakat-calculator/",
    locator: "How is Zakat calculated in 2026; ставка 2,5 % от нетто",
    language: "en",
    retrievedAt: RETRIEVED,
    terms: "институциональная методика",
    review: "institutional_page_checked",
    notes: "Активы минус допустимые обязательства, 2,5 %. Не покрывает таблицы скота в исходном HTML.",
  },
  {
    sourceId: "aaoifi.ss35.unverified",
    type: "institutional",
    title: "AAOIFI Shariah Standard 35 (Zakah) — полный текст не сверен",
    author: "AAOIFI",
    url: "https://aaoifi.com/",
    locator: "SS 35; публичный полный текст в этой среде не открыт",
    language: "en/ar",
    retrievedAt: RETRIEVED,
    terms: "не заявлять соответствие AAOIFI",
    review: "unverified",
    notes: "Упоминание AAOIFI в исходном HTML не подтверждено сверкой стандарта. Ветвь не считается реализованной как «соответствует AAOIFI».",
  },
  {
    sourceId: "kuwait.house.unverified",
    type: "institutional",
    title: "«Kuwait House» 85 г — ярлык исходного файла, первичный документ не найден",
    author: "не подтверждено",
    url: "",
    locator: "mizan-v3 original",
    language: "ru",
    retrievedAt: RETRIEVED,
    terms: "не использовать как подтверждённый профиль",
    review: "unverified",
    notes: "В исходнике был пункт kwh: 85 г. Первичный документ организации не найден; профиль не включён как проверенный.",
  },
  {
    sourceId: "nzf.proxy25.unverified",
    type: "institutional",
    title: "Оценочный коэффициент 25 % для инвестиций с неизвестной структурой",
    author: "встречается в ряде современных западных методик (в т.ч. упоминания NZF); полный первичный текст в этой среде не сверен",
    url: "",
    locator: "только при явном выборе пользователем",
    language: "en",
    retrievedAt: RETRIEVED,
    terms: "оценка, не хукм Корана/Сунны",
    review: "unverified",
    notes: "25 % не универсальная истина. Применяется исключительно как помеченная оценка в профилях, где пользователь явно выбрал режим proxy_25.",
  },
  {
    sourceId: "troy.ounce",
    type: "metrology",
    title: "Тройская унция = 31,1034768 г",
    author: "SI / NIST convention",
    url: "https://www.nist.gov/",
    locator: "1 troy ounce = 31.1034768 grams",
    language: "en",
    retrievedAt: RETRIEVED,
    terms: "метрология рынка металлов",
    review: "primary_text_checked",
    notes: "Нужна для перевода котировок XAU/XAG за унцию в цену за грамм. Не религиозный довод.",
  },
  {
    sourceId: "math.rate.1_40",
    type: "math",
    title: "Ставка 1/40 (2,5 %) для серебра и денежной аналогии",
    author: "Бухари 1454 (серебро); кийас на деньги — фикх/институты",
    url: "https://sunnah.com/bukhari:1454",
    locator: "«for silver the Zakat is one-fortieth»",
    language: "en/ar",
    retrievedAt: RETRIEVED,
    terms: "для серебра — хадис; для фиатных денег — аналогия",
    review: "primary_text_checked",
    notes: "Точная доля 1/40, не 0.025 с двоичной погрешностью float. Для урожая и риказа другие ставки.",
  },
  {
    sourceId: "crypto.screening.opinions",
    type: "institutional",
    title: "Панель мнений о криптоактивах (не хукм)",
    author: "сторонние списки и боты",
    url: "https://app.practicalislamicfinance.com/reports/crypto",
    locator: "PIF, CryptoUmmah, MRHB, A7kem, CryptoHalal и др.",
    language: "en/ru",
    retrievedAt: RETRIEVED,
    terms: "мнения, не окончательный хукм",
    review: "unverified",
    notes:
      "Источники для справки: cryptohalal_bot, MuslimBit_cryptobot, t.me/A7kem, t.me/MRHB_Shariah_Forum, cryptoummah.com/halal-crypto-list, practicalislamicfinance.com, t.me/CrypoIslam, CryptoGulfHalal_Bot. Коран и Сунна не содержат тикеров. Стейкинг/DeFi/лок требуют отдельного разбора права собственности.",
  },
];

export const SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(SOURCES.map((s) => [s.sourceId, s]));

export function getSources(ids: string[]): SourceRecord[] {
  return ids.map((id) => SOURCE_BY_ID[id]).filter(Boolean) as SourceRecord[];
}

export const CRYPTO_OPINION_LINKS = [
  { name: "@cryptohalal_bot", url: "https://t.me/cryptohalal_bot" },
  { name: "@MuslimBit_cryptobot", url: "https://t.me/MuslimBit_cryptobot" },
  { name: "t.me/A7kem", url: "https://t.me/A7kem" },
  { name: "MRHB Shariah Forum", url: "https://t.me/MRHB_Shariah_Forum" },
  { name: "CryptoUmmah Halal list", url: "https://cryptoummah.com/halal-crypto-list" },
  { name: "Practical Islamic Finance", url: "https://app.practicalislamicfinance.com/reports/crypto" },
  { name: "t.me/CrypoIslam", url: "https://t.me/CrypoIslam" },
  { name: "@CryptoGulfHalal_Bot", url: "https://t.me/CryptoGulfHalal_Bot" },
];
